# INSERT
INSERT INTO CLIENTE VALUES (NULL, 'PAOLA', 'M', 'PAOLA@EMAIL.COM', '123455123');

# SELECT
SELECT * FROM CLIENTE;

# UPDATE
SELECT * FROM CLIENTE WHERE IDCLIENTE = 23; # VERIFICA SE O ID BATE
UPDATE CLIENTE SET SEXO = 'F' WHERE IDCLIENTE = 23;

# DELETE
SELECT * FROM CLIENTE WHERE IDCLIENTE = 21; # VERIFICA SE O ID BATE
DELETE FROM CLIENTE WHERE IDCLIENTE = 21;