# CREATE TABLE
CREATE TABLE PRODUTO (
	IDPRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(32) NOT NULL,
    FRETE FLOAT(10, 2) NOT NULL,
    PRECO INT NOT NULL
);


# ALTER TABLE
## CHANGE
### É NECESSÁRIO PASSAR O NOME, O TIPO DE DADO E AS CONSTRAINTS MESMO QUE ELAS NÃO SEJAM ALTERADAS
ALTER TABLE PRODUTO CHANGE PRECO VALOR_UNITARIO FLOAT(10, 2) NOT NULL;
## MODIFY
ALTER TABLE PRODUTO MODIFY VALOR_UNITARIO VARCHAR(12) NOT NULL;

## ADD COLUMN
ALTER TABLE PRODUTO ADD COLUMN PESO FLOAT(10, 2);

### ADD COLUMN EM POSIÇÃO ESPECÍFICA
#### AFTER
ALTER TABLE PRODUTO ADD COLUMN PESO FLOAT(10,2) AFTER NOME;
#### FIRST
ALTER TABLE PRODUTO ADD COLUMN PESO FLOAT(10,2) FIRST;

## DROP COLUMN
ALTER TABLE PRODUTO DROP COLUMN PESO;


