# CRIAR VIEW
CREATE VIEW RELATORIO_CLIENTE AS
SELECT  C.NOME, 
		C.SEXO,
		C.EMAIL,
		C.CPF,
		IFNULL(T.TIPO, "N/A") AS TIPO,
		IFNULL(T.NUMERO, "N/A") AS NUMERO,
		E.BAIRRO,
		E.CIDADE,
		E.ESTADO,
		E.RUA
FROM CLIENTE C
INNER JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE;

# USAR VIEW
# USAR * AINDA NÃO É RECOMENDADO
SELECT * FROM RELATORIO_CLIENTE;

# MOSTRAR VIEWS
SHOW TABLES;

# DELETAR VIEW
DROP VIEW RELATORIO_CLIENTE;

# FAZER QUERY NA VIEW
SELECT NOME, ESTADO
FROM RELATORIO_CLIENTE;