# CRIAÇÃO DA TABELA
CREATE TABLE ALUNOS (
	# COLUNA 1
	NUMERO INT, 
    # COLUNA 2
    NOME VARCHAR(32)
);

# ORDERNAR PELO NÚMERO DA COLUNA
# O NÚMERO DA COLUNA É A ORDEM DE CRIAÇÃO QUANDO USANDO * E A ORDEM DA PROJEÇÃO QUANDO NÃO
SELECT * FROM ALUNOS ORDER BY 2;

# ORDENAR POR MAIS DE UMA COLUNA
# ORDERNA PELO NÚMERO E DEPOIS ORDENA OS REGISTROS DE MESMO NÚMERO (subconjunto) PELO NOME
SELECT * FROM ALUNOS ORDER BY NUMERO ASC, NOME DESC;

# ORDER BY NÃO INTERFERE NA PROJEÇÃO E VICE-VERSA
# É possível ordenar por um campo não projetado
SELECT NOME FROM ALUNOS ORDER BY NUMERO;
