# CRIAR PROCEDURE
## DEFINIR DELIMITER
DELIMITER $$
CREATE PROCEDURE PEGAR_CLIENTES()
BEGIN
	SELECT * FROM CLIENTE;
END $$
## REDEFINIR DELIMITER
DELIMITER ;


# USAR PROCEDURE
CALL PEGAR_CLIENTES();


# EXCLUIR PROCEDURE
DROP PROCEDURE PEGAR_CLIENTES;


## PROCEDURE COM PARAMS
DELIMITER $
CREATE PROCEDURE INSERT_CLIENTE(C_NOME VARCHAR(30), C_SEXO ENUM('F', 'M'), C_EMAIL VARCHAR(50), C_CPF VARCHAR(15))
BEGIN
	INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES
		(NULL, C_NOME, C_SEXO, C_EMAIL, C_CPF);
	SELECT * FROM CLIENTE WHERE IDCLIENTE = last_insert_id();
END $
DELIMITER ;


## CHAMAR PROCEDURE COM PARAMS
CALL INSERT_CLIENTE('LUCIANO COSTA ANT', 'M', 'LCCOSTA123@EMAIL.COM', '50980458100');


