# INNER QUERY QUE RETORNA UM REGISTRO
## O vendedor que vendeu menos em março e seu nome
SELECT NOME, MARCO AS 'VALOR'
FROM vendedores 
### O SELECT RETORNA O MENOR VALOR E O WHERE FILTRA COM BASE NESSE VALOR
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);


# INNER QUERY QUE RETORNA VÁRIOS REGISTROS
SELECT NOME, MARCO AS 'VALOR'
FROM vendedores 
WHERE MARCO IN(SELECT MARCO FROM VENDEDORES WHERE SEXO = 'F');