# OPERANDO COM LINHAS
SELECT NOME, 
	   JANEIRO,
       FEVEREIRO, 
       MARCO, 
		# FAZ A SOMA E A MEDIA DOS VALORES REGISTRO A REGISTRO (VENDEDOR A VENDEDOR)
       (JANEIRO + FEVEREIRO + MARCO) AS TOTAL_TRIMESTRE, 
       TRUNCATE((JANEIRO + FEVEREIRO + MARCO/3), 2) AS MEDIA_TRIMESTRE
FROM VENDEDORES;

# NÃO FUNCIONA POIS GERA ERRO DE SINTAXE E SE FUNCIONASSE SOMARIA O VALOR TOTAL
SELECT NOME, 
	   JANEIRO,
       FEVEREIRO, 
       MARCO, 
       SUM(JANEIRO, FEVEREIRO, MARCO) AS TOTAL_TRIMESTRE, 
       TRUNCATE(AVG(JANEIRO, FEVEREIRO, MARCO), 2) AS MEDIA_TRIMESTRE
FROM VENDEDORES;