CREATE TABLE COLUNAS (
	COLUNA1 INT,
    COLUNA2 INT,
    COLUNA3 INT 
);

# ADICIONAR PK
## NÃO É POSSÍVEL USAR AUTO_INCREMENT
ALTER TABLE COLUNAS 
ADD PRIMARY KEY(COLUNA1);

# ALTERAR TIPO DA COLUNA
ALTER TABLE COLUNAS
MODIFY COLUNA2 VARCHAR(32);

# ADICIONAR FK
ALTER TABLE COLUNAS
ADD FOREIGN KEY(COLUNA3) REFERENCES CLIENTE(IDCLIENTE);

# RENOMEAR TABELA
ALTER TABLE COLUNAS RENAME TABELA;

# VER OS METADADOS DE UMA TABELA DE MANEIRA MAIS DESCRITIVA
SHOW CREATE TABLE TABELA;