CREATE TABLE CLIENTE(
	IDCLIENTE INT AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    PRIMARY KEY PK_CLIENTE (IDCLIENTE)
);

# CRIAR A TABELA SEM FK
CREATE TABLE TELEFONE(
    IDTELEFONE INT AUTO_INCREMENT PRIMARY KEY,
	IDCLIENTE INT,
    TIPO CHAR(3) NOT NULL,
    NUMERO VARCHAR(11) NOT NULL
);

# DEFINIR A FK DEPOIS DE CRIAR AS TABELAS
ALTER TABLE TELEFONE
ADD CONSTRAINT FK_CLIENTE_TELEFONE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);


# DELETAR CONSTRAINT PELO NOME
## É POSSÍVEL DELETAR A CONSTRAINT USANDO SEU NOME
ALTER TABLE TELEFONE
DROP FOREIGN KEY FK_CLIENTE_TELEFONE;