# USAR O DB COM DICIONÁRIO DE DADOS
USE INFORMATION_SCHEMA;

# PROCURAR PELA TABELA COM OS DADOS DESEJADOS
SHOW TABLES;

# DESCREVER A TABELA 
## TABLE_CONSTRAINTS = CONSTRAINTS
DESC TABLE_CONSTRAINTS;

# FAZER UM SELECT
## Mostra as constraints das tabelas cliente e telefone do schema comercio
SELECT CONSTRAINT_NAME AS 'Nome', 
	   CONSTRAINT_TYPE AS 'Tipo', 
       TABLE_NAME AS 'Tabela', 
       TABLE_SCHEMA AS 'DB'
FROM TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'comercio' AND TABLE_NAME IN('cliente', 'telefone');