CREATE DATABASE OFICINA;
USE OFICINA;

# TABELAS
CREATE TABLE CLIENTE (
	IDCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
	IDCARRO INT,
    NOME VARCHAR(32) NOT NULL,
    CPF VARCHAR(11) NOT NULL
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT AUTO_INCREMENT PRIMARY KEY,
    IDCLIENTE INT, 
    TIPO CHAR(3),
    NUMERO VARCHAR(10) NOT NULL
);

CREATE TABLE CARRO (
	IDCARRO INT AUTO_INCREMENT PRIMARY KEY,
    IDMARCA INT,
    MODELO VARCHAR(32) NOT NULL,
    CHASSI VARCHAR(17) NOT NULL
);

CREATE TABLE MARCA (
	IDMARCA INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE COR (
	IDCOR INT AUTO_INCREMENT PRIMARY KEY,
    COR VARCHAR(12) NOT NULL UNIQUE
);

## TABELA ASSOCIATIVA
CREATE TABLE CARRO_COR (
	IDCARRO INT,
    IDCOR INT,
    PRIMARY KEY(IDCARRO, IDCOR)
);

# FKS
## CLIENTE
ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(IDCARRO) REFERENCES CARRO(IDCARRO);

## TELEFONE
ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

## MARCA
ALTER TABLE CARRO 
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(IDMARCA) REFERENCES MARCA(IDMARCA);

## ASSOCIATIVA
ALTER TABLE CARRO_COR 
ADD CONSTRAINT FK_CARRO_COR
FOREIGN KEY(IDCARRO) REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR_CARRO
FOREIGN KEY(IDCOR) REFERENCES COR(IDCOR);