# SINTAXE BÁSICA
## ALTERAR DELIMITER
DELIMITER $

CREATE TRIGGER NOME
AFTER INSERT ON TABELA # PODE Ser BEFORE ou AFTER e o comando pode ser INSERT, DELETE ou UPDATE
FOR EACH ROW 
BEGIN
    COMANDOS;
END$

DELIMITER ;

# TRIGGER PARA FAZER BACKUP ANTES DE DELETAR UM USUÁRIO
DELIMITER $
CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON user
FOR EACH ROW
BEGIN
	INSERT INTO bkp_user (idbkp, iduser, name, email, username)
    # OLD = valores na tabela
    VALUES (NULL, OLD.iduser, OLD.name, OLD.email, OLD.username);
END$
DELIMITER ;

# TRIGGER PARA FAZER UM LOG COM O USUÁRIO QUE ALTEROU E A DATA DE ALTERAÇÃO
DELIMITER $

CREATE TRIGGER NOME
AFTER UPDATE ON user
FOR EACH ROW 
BEGIN
    INSERT INTO backup.logUser (idlog, iduser, name, email, username, changeDate, author)
    ## CURRENT_USER RETORNA O USUÁRIO ATUAL
    VALUES (NULL, OLD.iduser, OLD.name, OLD.email, OLD.username, NOW(), CURRENT_USER());
END$

DELIMITER ;


# EXCLUIR TRIGGER

DROP TRIGGER NOME;