DELIMITER $
CREATE PROCEDURE VENDEDORES_CURSOR()
BEGIN
    # DECLARAR VARIÁVEIS 
	DECLARE FIM INT DEFAULT 0;
    DECLARE MAR, FEV, JAN INT;
    DECLARE VSOMA FLOAT(10,2);
    
    # DECLARAR CURSOR
    DECLARE V_CURSOR CURSOR FOR (SELECT JANEIRO, FEVEREIRO, MARCO FROM VENDEDORES);
    
    # DECLARAR CONTINUE HANDLER
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
    
    ## ABRE O CURSOR EM MEMÓRIA
	OPEN V_CURSOR;
    
    # LOOP
    REPEAT
		# FETCH GUARDA OS VALORES DO ÍNDICE ATUAL NAS VARIÁVEIS E PASSA PARA O PRÓXIMO ÍNDICE
        ## ORDEM DO SELECT
        FETCH V_CURSOR INTO JAN, FEV, MAR;
        
        # VERIFICA SE NÃO É O FIM DO LOOP
        IF NOT FIM THEN
        
			# SET seta o valor da variável
			SET VSOMA = JAN + FEV + MAR;
            
            # MAIS ALGUNS COMANDOS
		END IF;
	# FECHA O LOOP QUANDO FIM É VERDADEIRO
	UNTIL FIM END REPEAT;
    
END$
DELIMITER ;