CREATE DATABASE COMERCIO;
USE COMERCIO;

# NÃO HÁ FKs, então a modelagem física está errada

CREATE TABLE CLIENTE (
    # PK com auto_increment
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('F', 'M') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(64) NOT NULL,
    CIDADE VARCHAR(32) NOT NULL,
    ESTADO VARCHAR(32) NOT NULL,
    BAIRRO VARCHAR(32) NOT NULL
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CEL', 'RES', 'COM') NOT NULL,
    NUMERO VARCHAR(10)
);


