# DESCREVER CAMPOS NA TABELA
DESC CLIENTE;


# INSERIR COM PK AUTO_INCREMENT
# PASSAR NULL EM VEZ DE UM VALOR
INSERT INTO CLIENTE VALUES 
(NULL, 'JOSE', 'M', 'JOSE@EMAIL.COM', '12345678910'),
(NULL, 'LUCAS', 'M', 'LUCAS@EMAIL.COM', '12345678911'),
(NULL, 'LUCIANO', 'M', 'LUCIANO@EMAIL.COM', '12345678912'),
(NULL, 'LETICIA', 'F', 'LETICIA@EMAIL.COM', '12345678913'),
(NULL, 'ANA', 'F', 'ANA@EMAIL.COM', '12345678914'),
(NULL, 'FERNANDA', 'F', 'FERNANDA@EMAIL.COM', '12345678915'),
(NULL, 'LUCIO', 'M', 'LUCIO@EMAIL.COM', '12345678916');


# INSERINDO COM FK E RELAÇÃO (1, 1)
# LEVAR EM CONTA A INTEGRIDADE REFERENCIAL, O CAMPO DA FK DEVE EXISTIR DE FATO
INSERT INTO ENDERECO VALUES (NULL, 1, 'ANTONIO CARLOS JOSÉ', 'SÃO PAULO', 'SP', 'VILA CLOTILDE');

# UTILIDADE DO UNIQUE
# UNIQUE GARANTE O (1, 1)
# UNIQUE NÃO DEIXA ASSOCIAR OUTRO ENDEREÇO AO MESMO CLIENTE
INSERT INTO ENDERECO VALUES (NULL, 1, 'STALINGRADO', 'SÃO PAULO', 'SP', 'VILA CLOTILDE');


# INSERT COM FK E RELAÇÃO (1, N)
INSERT INTO TELEFONE VALUES (NULL, 1, 'CEL', '1198777');
INSERT INTO TELEFONE VALUES (NULL, 1, 'CEL', '1198888');
