# WHERE EM JUNÇÕES
# JUNÇÃO COM WHERE SÓ PARA JUNÇÃO
SELECT NOME, BAIRRO, EMAIL # PROJEÇÃO
FROM CLIENTE, ENDERECO # ORIGEM
WHERE IDCLIENTE = ID_CLIENTE; # JUNÇÃO

# WHERE PARA JUNÇÃO E SELEÇÃO
SELECT NOME, BAIRRO, EMAIL # PROJEÇÃO
FROM CLIENTE, ENDERECO # ORIGEM
WHERE IDCLIENTE = ID_CLIENTE # JUNÇÃO (COMPARAÇÃO REDUNDANTE)
AND IDCLIENTE = 1; # SELEÇÃO


# INNER JOIN COM ON
SELECT NOME, BAIRRO, EMAIL # PROJEÇÃO
FROM CLIENTE # ORIGEM
INNER JOIN ENDERECO # JUNÇÃO
	ON IDCLIENTE = ID_CLIENTE # CAMPO EM COMUM DA JUNÇÃO
WHERE IDCLIENTE = 1; # SELEÇÃO

# INNER JOIN COM USING
SELECT NOME, BAIRRO, EMAIL # PROJEÇÃO
FROM CLIENTE # ORIGEM
INNER JOIN ENDERECO # JUNÇÃO
	USING (IDCLIENTE) # CAMPO EM COMUM DA JUNÇÃO
WHERE IDCLIENTE = 1; # SELEÇÃO


# INNER JOIN DUPLO
/* CASO UM CAMPO TENHA O MESMO NOME NAS TABELAS DE JOIN 
É NECESSÁRIO USAR UM ALIAS PARA EVITAR AMBIGUIDADE OU USAR NOMEDATABELA.CAMPO*/
SELECT c.NOME, c.SEXO, a.BAIRRO, a.CIDADE, b.TIPO, b.NUMERO
FROM CLIENTE c
INNER JOIN ENDERECO a ON c.IDCLIENTE = a.ID_CLIENTE
INNER JOIN TELEFONE b ON c.IDCLIENTE = b.ID_CLIENTE;
