# CRIANDO O DB
CREATE DATABASE PROJETO;

# ACESSANDO O DB
USE PROJETO;

# CRIANDO CLIENTES
CREATE TABLE clientes (
	nome VARCHAR(30),
    cpf INT(11),
    email VARCHAR(30),
    telefone VARCHAR(12),
	endereco VARCHAR(120),
    sexo CHAR(1)
);

# MOSTRAR TABELAS DO SCHEMA SELECIONADO
SHOW TABLES;

# DESCREVER TABELA DO SCHEMA SELECIONADO
DESC clientes;