# INSERIR OMITINDO COLUNAS
INSERT INTO clientes VALUES 
('RODRIGO', 1234543210, 'RODRIGO@EXAMPLE.COM', 11977777777, 'RUA XYZ', 'M');

# INSERIR DECLARANDO COLUNAS
# CAMPO TELEFONE OMITIDO (NULL)
INSERT INTO clientes (NOME, CPF, EMAIL, ENDERECO, SEXO) VALUES 
('LUIS', 1234543210, 'LUIS@EXAMPLE.COM', 'RUA XYZ', 'M');