# FILTRAR SELECT COM WHERE
SELECT NOME, ENDERECO FROM CLIENTES WHERE SEXO = 'F';

# OPERADOR LIKE
SELECT NOME, ENDERECO FROM CLIENTES WHERE NOME LIKE '%M';

# OP. LÓGICOS
## OR
SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';

## AND
SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

## NOT
SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' AND ENDERECO NOT LIKE '%ESTACIO';
