# DESABILITA SAFE UPDATES
SET SQL_SAFE_UPDATES = 0;

# INSERT
INSERT INTO V_RELATORIO VALUES(
'ANDREIA','F','ANDREIA@UOL.COM.BR','CEL','873547864','CENTRO','VITORIA','ES'
);
# GERA O ERRO 1394 (HY000): Can not insert into join view 'comercio.v_relatorio' without fields list

# DELETE
DELETE FROM V_RELATORIO WHERE NOME = 'JORGE';
# GERA O ERRO 1395 (HY000): Can not delete from join view 'comercio.v_relatorio'

# UPDATE (OCORRE NORMALMENTE E É REFLETIDO NA TABELA)
UPDATE V_RELATORIO SET NOME = 'LUCAS' WHERE NOME = 'JORGE';

SET SQL_SAFE_UPDATES = 1;